tx = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(tx))
print('Só tem espaços? ', a.isspace())
print('É um numeró? ', a.isnumeric())
print('É alfabetico? ', a.isalpha())
print('Esta em maiusculas? ', a.isupper())
print('Esta em minuscula? ', a.islower())
