nome = str(input('Digite seu nome completo: ')).strip()
print('Analisando seu nome...')
print('Seu nome em maiusculo é {}' .format(nome.upper()))
print('Seu nome em misnusculo é {}' .format(nome.lower()))
print('Seu nome tem ao todo {}' .format(len(nome) - nome.count(' ')))
print('Seu primeiro nome é {} e ele tem {} letras'.format(nome.split()[0], len(nome.split()[0])))